/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author sastian
 */
public class VerInformacionIndividual extends javax.swing.JPanel {

    /**
     * Creates new form VerInformacionIndividual
     */
    public VerInformacionIndividual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombreTerminal = new javax.swing.JLabel();
        imagen = new imageView.ImageView();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombreTerminal.setBackground(new java.awt.Color(153, 153, 153));
        jLabelNombreTerminal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelNombreTerminal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreTerminal.setText("Nombre Terminal");
        add(jLabelNombreTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 360, 30));
        add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/B94.jpg"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -40, 840, 520));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private imageView.ImageView imagen;
    private javax.swing.JLabel jLabelNombreTerminal;
    // End of variables declaration//GEN-END:variables
}
